### ISSUE TITLE
Add windows support to justfile

### ISSUE THREAD

**Issue by ccunningham101** [iaindillingham/cohort-joiner#40]
Current justfile does not work on Windows
This will affect anyone who might want to develop and test reusable actions on Windows
Investigate whether adding windows support as was done in the [repo-template](https://github.com/opensafely-core/repo-template/pull/53) will work here

**Comment by Jongmassey** [comment]
Justfile as per https://github.com/opensafely-core/repo-template/commit/7ab8eab31c5d5cbe0add902124b498fe68617951 runs fine in git-bash on windows; but installing the requirements listed in repo-template fails with the following:


```
Collecting typing-extensions>=3.10.0.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.10.0.0 from https://files.pythonhosted.org/packages/75/e1/932e06004039dd670c9d5e1df0cd606bf46e29a28e65d5bb28e894ea29c9/typing_extensions-4.2.0-py3-none-any.whl#sha256=6657594ee297170d19f67d55c05852a874e7eb634f4f753dbd667855e07c1708 (from black==22.3.0->-r requirements.dev.txt (line 17))```


In my experience, manually installing the dependent requirement which is un-pinned is a way of working around this; whereas no workarounds for the problems encountered with the old version of the justfile were found
